incomingPort: 8123
outgoingPort: 8124
deviceAddress: 192.168.1.2

multiToggle:
    name: /1/multitoggle1
    multiToggleRows:
        - sounds:
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
        - sounds:
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
            - soundPath: "/path/to/sound-file.wav"
