incomingPort: 8123
outgoingPort: 8124
deviceAddress: 192.168.179.34
sounds:
  - oscAddress: "/1/multitoggle1/1/1"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/crickets.wav"
  - oscAddress: "/1/multitoggle1/2/1"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/crickets.wav"
  - oscAddress: "/1/multitoggle1/3/1"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/crickets.wav"
  - oscAddress: "/1/multitoggle1/4/1"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/crickets.wav"
  - oscAddress: "/1/multitoggle1/5/1"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/crickets.wav"
  - oscAddress: "/1/multitoggle1/6/1"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/crickets.wav"
  - oscAddress: "/1/multitoggle1/7/1"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/crickets.wav"
  - oscAddress: "/1/multitoggle1/8/1"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/crickets.wav"
  - oscAddress: "/1/multitoggle1/9/1"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/crickets.wav"

  - oscAddress: "/1/multitoggle1/1/2"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/2/2"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/3/2"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/4/2"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/5/2"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/6/2"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/7/2"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/8/2"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/9/2"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"

  - oscAddress: "/1/multitoggle1/1/3"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/2/3"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/3/3"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/4/3"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/5/3"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/6/3"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/7/3"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/8/3"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/9/3"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"

  - oscAddress: "/1/multitoggle1/1/4"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/2/4"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/3/4"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/4/4"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/5/4"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/6/4"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/7/4"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/8/4"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/9/4"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"

  - oscAddress: "/1/multitoggle1/1/5"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/2/5"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/3/5"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/4/5"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/5/5"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/6/5"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/7/5"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/8/5"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/9/5"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"

  - oscAddress: "/1/multitoggle1/1/6"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/2/6"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/3/6"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/4/6"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/5/6"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/6/6"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/7/6"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/8/6"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/9/6"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"

  - oscAddress: "/1/multitoggle1/1/7"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/2/7"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/3/7"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/4/7"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/5/7"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/6/7"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/7/7"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/8/7"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"
  - oscAddress: "/1/multitoggle1/9/7"
    soundPath: "/Users/ferdi/Dropbox/podcasting/soundboard/but-im-le-tired.wav"